### ISSUE TITLE
Optionally use http instead of https

### ISSUE THREAD

**Issue by jboesch** [Znarkus/postmark-php#7]
Would it be possible to have a constant to say whether or not to use http or https?

**Comment by Znarkus** [comment]
Why would you want that, if I may ask?

**Comment by jboesch** [comment]
I was getting errors on my server for not finding the certificate info, even though I had the Certificate folder from the download.  It was throwing exceptions about the certificate and looking in /etc/ssl or something... I wasn't sure what to do so I just stripped out the curl info that did SSL and removed the "s" from "https".

**Comment by jboesch** [comment]
Also, if the API gives you the option to do http or https (http://developer.postmarkapp.com/developer-build.html) then I think this lib should as well.

Don't get me wrong, I'm very grateful for all the work that has been done it :)

**Comment by Znarkus** [comment]
I'm sorry but I must disagree. If I would to add this option, it will encourage people not to use SSL. Just because it saves them a couple of minutes in initial setup.

I recommend you to try to fix the problem you were having, instead of disabling secure transfers of the e-mail. If you give me a little more detail, I'd be happy to help you out.
